{
	"___resource_file_intro"		:	"Mit dieser Formatierung werden von JSON erforderte Kommata oder Doppelpunkte nie mehr vergessen. Für neue Ressourcen, copy&paste folgende Zeile."
,	"x"								:	"y"
,	"maintemplate_loading"			:	"Wird geladen"
,	"maintemplate_nohub_title"		:	"Noch kein Hub eingerichtet"
,	"maintemplate_nohub_desc"		:	"Dieser Server enthält noch keine Hubs."
,	"log_mongo_dbconnected"			:	"Verbunden mit {0}-Datenbank."
,	"log_mongo_error_dbnoconnect"	:	"FEHLER beim Verbinden mit {0}-Datenbank:\n{1}"
,	"log_mongo_error_start"			:	"FEHLER beim Starten von MongoDB:\n{0}"
,	"log_pack_nocorepack"			:	"FEHLER beim Laden von erforderlichem Paket '{0}'; Abbruch."
,	"log_pack_loading"				:	"PAKET '{0}': wird geladen..."
,	"log_pack_error_depends1"		:	"Erfordert Paket '{0}', welches in dieser smoothio-Instanz nicht installiert ist."
,	"log_pack_error_depends2"		:	"Erfordert Paket '{0}', welches installiert ist, aber nicht erfolgreich geladen wurde."
,	"log_pack_error_notloaded"		:	"FEHLER beim Laden von Paket '{0}':\n{1}"
,	"log_pack_error_compile"		:	"Fehler bei Kompilierung:\n{1}"
,	"log_pack_loaded"				:	"PAKET '{0}': erfolgreich geladen."
,	"log_server_error_start"		:	"FEHLER beim Starten von SERVER '{0}':\n{1}"
,	"log_server_listening"			:	"SERVER '{0}' gestartet unter {1}:{2}"
,	"log_server_closing"			:	"Anhalten..."
,	"log_server_closed"				:	"Beendet."
}

