{
	"___resource_file_intro"		:	"This formatting ensures no JSON-required commas or colons are ever missed. To add new resources, copy&paste the next line."
,	"x"								:	"y"
,	"close"							:	"Close"
,	"connecting"					:	"Connecting"
,	"connecting_hint"				:	"Either your network connection or our server is down. You will be reconnected shortly."
,	"natlangtime_future"			:	"in %s"
,	"natlangtime_past"				:	"%s ago"
,	"natlangtime_s"					:	"a moment"
,	"natlangtime_m"					:	"a minute"
,	"natlangtime_mm"				:	"%d minutes"
,	"natlangtime_h"					:	"an hour"
,	"natlangtime_hh"				:	"%d hours"
,	"natlangtime_d"					:	"a day"
,	"natlangtime_dd"				:	"%d days"
,	"natlangtime_M"					:	"a month"
,	"natlangtime_MM"				:	"%d months"
,	"natlangtime_y"					:	"a year"
,	"natlangtime_yy"				:	"%d years"
,	"timeout"						:	"This request timed out before receiving a response from the server, and may or may not have been processed by now."
}

