resources['de'] = {
	"___resfile_intro"	:	"DIESE RES.*.JS-DAIEI: durch die hier verwendete Formatierung werden von JSON erforderte Kommata oder Doppelpunkte nie mehr vergessen. Copy&Paste für neue Ressourcen"
,	"config_db"			:	"Datenbankzugriff"
,	"config_db_am"		:	"Datenbankmodus"
,	"h_config_db_am"	:	"Eingebettet: smoothio führt einen eigenen lokalen MongoDB-Server aus; Datendateien werden in einem instanzeigenen Unterordner gehalten.\n\nExtern: smoothio verbindet sich mit einem externen, von dieser smoothio-Instanz komplett unabhängig verwalteten und ausgeführten MongoDB-Server."
,	"config_db_am_em"	:	"eingebettet"
,	"config_db_am_ex"	:	"extern"
,	"config_db_host"	:	"DB-Server"
,	"h_config_db_host"	:	"Eingebetteter Modus: immer 127.0.0.1.\n\nExterner Modus: geben Sie die IP-Adresse oder den Hostnamen des externen MongoDB-Servers an. (Läuft der externe MongoDB-Server auf dieser Maschine, kann auch localhost verwendet werden, nicht jedoch 127.0.0.1.)"
,	"config_db_port"	:	"Port"
,	"h_config_db_port"	:	"Eingebetteter Modus: gibt die TCP-Portnummer an, unter welcher der lokale MongoDB-Datenbankserver Verbindungen akzeptieren soll.\n\nExterner Modus: gibt die TCP-Portnummer an, unter welcher der externe MongoDB-Datenbankserver Verbindungen akzeptiert."
,	"config_db_path"	:	"Datenpfad"
,	"h_config_db_path"	:	"Nur eingebetteter Modus. Gibt den (immer zum Instanzverzeichnis relativen) Verzeichnispfad zur Speicherung von smoothios administrativen und Inhaltsdatenbanken an."
,	"config_db_log"		:	"Logdateipfad"
,	"h_config_db_log"	:	"Nur eingebetteter Modus. Gibt den (immer zum Instanzverzeichnis relativen) Dateipfad zur Speicherung von MongoDB-Logausgaben an.\n\nUm das Überschreiben älterer Logdateien zu verhindern, können Sie in diesem Dateipfad ein Sternchen [*] unterbringen (wird bei Erstellung der Logdatei durch aktuelle/s Datum+Uhrzeit ersetzt)."
,	"config_db_au"		:	"Benutzername"
,	"h_config_db_au"	:	"Nur externer Modus. Falls der externe MongoDB-Datenbankserver Authentifizierung erfordert, hier den Anmeldebenutzernamen angeben."
,	"config_db_ap"		:	"Kennwort"
,	"h_config_db_ap"	:	"Nur externer Modus. Falls der externe MongoDB-Datenbankserver Authentifizierung erfordert, hier das Anmeldekennwort angeben.\n\nACHTUNG: dies wird unverschlüsselt im Klartext in der instance.config-Datei gespeichert. Diese Datei entsprechend sichern, so daß nur Sie und das lokale smoothio-Dienstkonto darauf zugreifen können."
,	"config_db_ar"		:	"DB-Server erfordert Authentifizierung"
,	"config_dns"		:	"Instanzserver-Hostnamen vor-aufl&ouml;sen"
,	"config_dns_p"		:	"DNS &amp; Windows..."
,	"h_config_dns_p"	:	"Manuelle Vor-Auflösung von Servernamen unter Umgehung von DNS:\n\nAuf Windows-Maschinen dringend erforderlich; auf anderen Systemen nicht weiter nützlich. Die manuelle Zuordnung des lokalen Maschinennamens sowie 'localhost' zur IP-Adresse 127.0.0.1 ist unter Windows erforderlich, damit die für diese Instanz definierten Server korrekt gestartet werden können -- denn sobald die Maschine nicht auf (die unter _core\\bin\\windows\\etc\\resolv.conf definierten) DNS-Server zugreifen kann (z.B. wenn Windows offline ist), kann die von smoothio verwendete Cygwin-Umgebung nicht mal Ihren Maschinennamen oder 'localhost' erfolgreich nach 127.0.0.1 auflösen und Ihre Instanzserver können nicht gestartet werden.\n\nJede Zeile enthält eine Zuordnung aus einem Hostname und seiner IP-Adresse, getrennt durch Doppelpunkt, z.B. meinserver:127.0.0.1\n\nDer spezielle Hostname \'$localhostname\' entspricht immer dem Namen der lokalen Maschine. Selbstverständlich funktionieren für die Bindung Ihrer Instanzserver hier nur Hostnamen und IP-Adressen, die dieser Maschine auch bereits (durch die entsprechende OS-Netzwerkkonfiguration) zugeordnet sind."
,	"config_log_path"	:	"Logdateipfad"
,	"config_log_d"		:	"Bei Loggen von Fehlern Details ausgeben"
,	"config_log_s"		:	"Bei Fehlern Stapelverfolgung loggen"
,	"h_config_log_path"	:	"Gibt den (immer zum Instanzverzeichnis relativen) Dateipfad zur Speicherung von Instanz-Logausgaben an.\n\nUm das Überschreiben älterer Logdateien zu verhindern, können Sie in diesem Dateipfad ein Sternchen [*] unterbringen (wird bei Erstellung der Logdatei durch aktuelle/s Datum+Uhrzeit ersetzt)."
,	"config_log_lang"	:	"Standardsprache"
,	"config_log_lang_o"	:	"Andere:"
,	"h_config_log_lang"	:	"Gibt die Sprache an, die für Logausgaben dieser smoothio-Instanz verwendet wird und entspricht gleichzeitig der initialen Inhaltssprache, die für neu erstellte Server und Sites in dieser Instanz festgelegt wird."
,	"config_rs_cf"		:	"Instanz-Neustart"
,	"h_config_rs_cf"	:	"Diese Option ankreuzen, wenn sich diese Instanz bei Änderungen an bestimmten Quelldateien (z.B. Script-, Style- oder Konfigurationsdateien in benutzerdefinierten Paketen) automatisch neu starten soll.\n\nEmpfohlen für Entwicklersysteme während des Entwurfs benutzerdefinierter Pakete. Nicht empfohlen für Produktivsysteme, um nicht unnötig nur zur Überwachung von Dateien Systemressourcen zu reservieren.\n\nHINWEIS: unabhängig von dieser Einstellung startet sich diese Instanz IMMER neu, sobald ihre instance.config-Datei modifiziert wird."
,	"config_rs_cfl"		:	"bei &Auml;nderungen von Kern-Quelldateien"
,	"config_rs_fc"		:	"...bei Fatal Crash"
,	"h_config_rs_fc"	:	"Damit der Instanzprozess nie Clientanfragen in einem inkonsistenten, unzuverlässigen Zustand bedient, wird dieser bei einem \"Fatal Crash\" (ein Fehler, welcher von smoothio nicht abgefangen und sauber behandelt werden konnte) grundsätzlich heruntergefahren.\n\nFür solche Fälle wird empfohlen, die Instanz sofort automatisch neustarten zu lassen, jedoch empfiehlt sich dieses Verhalten nicht für fatale Fehler noch während der Startphase der Instanz oder sehr kurz danach.\n\nGeben Sie die Mindest-Uptime (in Sekunden) an, die erreicht sein muß, bevor sich diese Instanz bei einem fatalen Fehler selbst neustarten kann. Wurde diese Mindest-Uptime bei solch einem Fehler nicht erreicht, schaltet sich die Instanz einfach nur selbst ab und wird bis zum nächsten Neustart von smoothio Daemon nicht neugestartet."
,	"config_rs_fcl"		:	"nur wenn Uptime in Sekunden l&auml;nger als"
,	"config_unsaved"	:	"<b>Ungespeicherte</b> &Auml;nderungen. <a href=\"#\" onclick=\"smio.configSaveChanges();\">Speichern</a> (o. Konfiguration <a href=\"#\" onclick=\"smio.refreshUI(false, false, true);\">neu laden</a>)."
,	"config_info"		:	"Zur Anzeige einer Kurzinfo für eine Einstellung deren Namen anklicken."
,	"config_general"	:	"Allgemein"

,	"daemon_confirm1"	:	"Wenn Sie jetzt fortfahren, wird der smoothio Daemon"
,	"daemon_confirm2"	:	" neu gestartet und für etwa 2-6 Sekunden nicht verfügbar sein.\n\nDies sollte gemeinhin keine zu störende Unterbrechung für die meisten aktiven Benutzer darstellen, jedoch werden sämtliche laufenden Vorgänge wie Dateiuploads und Downloads etc. abgebrochen (für alle Server aller Instanzen)."
,	"daemon_confirm3"	:	" heruntergefahren.\n\nAlle aktiven Benutzerverbindungen werden getrennt und sämtliche laufenden Vorgänge wie Dateiuploads und Downloads etc. werden abgebrochen (für alle Server aller Instanzen)."
,	"daemon_confirm4"	:	"\n\nTrotzdem fortfahren?"

,	"info_for"			:	"f&uuml;r"
,	"info_arch"			:	"Architektur:"
,	"info_procs"		:	"Prozessoren / Kerne:"

,	"subtab_config"		:	"Konfiguration"
,	"subtab_logs"		:	"Logs"
,	"subtab_overview"	:	"&Uuml;berblick"
,	"subtab_servers"	:	"Server"

,	"tabs_insterror1"	:	"Die Instanz '"
,	"tabs_insterror2"	:	"' konnte nicht geladen werden:"
,	"tabs_title1"		:	"<b>"
,	"tabs_title2"		:	"</b>-Instanz"
,	"tabs_welcome"		:	"Willkommen"

,	"tray_hint"			:	"smoothio Monitor"
,	"tray_menu_exit"	:	"smoothio Monitor beenden"
,	"tray_menu_show"	:	"smoothio Monitor öffnen"

,	"toolbar_refresh"	:	"Aktualisieren"
,	"toolbar_restart"	:	"Neu starten"
,	"toolbar_start"		:	"Starten"
,	"toolbar_status"	:	"smoothio Daemon-Status:"
,	"toolbar_status_0"	:	"Angehalten"
,	"toolbar_status_1"	:	"Gestartet"
,	"toolbar_status_2"	:	"Wird gestartet"
,	"toolbar_status_3"	:	"Wird beendet"
,	"toolbar_status_10"	:	"Unbekannt"
,	"toolbar_stop"		:	"Beenden"
, 	"toolbar_wait"		:	"(wird ermittelt...)"

, 	"welcome_headline"	:	"So verwenden Sie smoothio Monitor:"
, 	"welcome_para1"		:	"Die linke Navigation listet Ihre <b>smoothio-Instanzen</b> auf. Sobald und solange der <b>smoothio Daemon</b> l&auml;uft, stellt dieser die Ausf&uuml;hrung und Verf&uuml;gbarkeit dieser Instanzen sicher."
, 	"welcome_para2"		:	"Jede <b>smoothio-Instanz</b> wird als eigener Prozess ausgef&uuml;hrt und kann mehrere <b>smoothio-Server</b> unterhalten (jene Sites, welche Ihre Anwender besuchen). Oft gen&uuml;gt eine einzige Instanz."
, 	"welcome_para3"		:	"Zur Überwachung oder Konfiguration einer <b>smoothio-Instanz</b> w&auml;hlen Sie diese links aus. Sie k&ouml;nnen dann Logdateien sowie die grundlegende Instanzkonfiguration, als auch ihre <b>smoothio-Server</b> und deren Datenbankzugriff einsehen bzw. anpassen."
, 	"welcome_para4"		:	"<em>Hinweis:</em> dies ist ein Werkzeug zur &quot;niederen&quot; Daemon/Server-Verwaltung und &Uuml;berwachung. Weiterf&uuml;hrende &uuml;bergeordnete administrative Werkzeuge sowie detailliertere Dokumentation finden Sie in Ihren smoothio-Sites, sobald und solange Ihre Instanzen und deren Server &uuml;ber Ihren Webbrowser erreichbar sind."
,	"welcome_summary"	:	"Aktuell laufende smoothio-Server:"
};

