resources['de'] = {
	"_"					:	""
,	"info_for"			:	"f&uuml;r"
,	"info_arch"			:	"Architektur:"
,	"info_procs"		:	"Prozessoren / Kerne:"
,	"subtab_config"		:	"Konfiguration"
,	"subtab_logs"		:	"Logs"
,	"subtab_overview"	:	"&Uuml;berblick"
,	"subtab_servers"	:	"Server"
,	"tabs_insterror1"	:	"Die Instanz '"
,	"tabs_insterror2"	:	"' konnte nicht geladen werden:"
,	"tabs_title1"		:	"<b>"
,	"tabs_title2"		:	"</b>-Instanz"
,	"tabs_welcome"		:	"Willkommen"
,	"tray_hint"			:	"smoothio Monitor"
,	"tray_menu_exit"	:	"smoothio Monitor beenden"
,	"tray_menu_show"	:	"smoothio Monitor öffnen"
,	"toolbar_refresh"	:	"Aktualisieren"
,	"toolbar_restart"	:	"Neu starten"
,	"toolbar_start"		:	"Starten"
,	"toolbar_status"	:	"smoothio Daemon-Status:"
,	"toolbar_status_0"	:	"Angehalten"
,	"toolbar_status_1"	:	"Gestartet"
,	"toolbar_status_2"	:	"Wird gestartet"
,	"toolbar_status_3"	:	"Wird beendet"
,	"toolbar_status_10"	:	"Unbekannt"
,	"toolbar_stop"		:	"Beenden"
, 	"toolbar_wait"		:	"(wird ermittelt...)"
, 	"welcome_headline"	:	"So verwenden Sie smoothio Monitor:"
, 	"welcome_para1"		:	"Die linke Navigation listet Ihre <b>smoothio-Instanzen</b> auf. Sobald und solange der <b>smoothio Daemon</b> l&auml;uft, stellt dieser die Ausf&uuml;hrung und Verf&uuml;gbarkeit dieser Instanzen sicher."
, 	"welcome_para2"		:	"Jede <b>smoothio-Instanz</b> wird als eigener Prozess ausgef&uuml;hrt und kann mehrere <b>smoothio-Server</b> enthalten (jene Sites, welche Ihre Anwender besuchen). Anfangs bzw. meistens gen&uuml;gt eine einzige Instanz."
, 	"welcome_para3"		:	"Zur Überwachung oder Konfiguration einer <b>smoothio-Instanz</b> w&auml;hlen Sie diese links aus. Sie k&ouml;nnen dann Logdateien sowie die grundlegende Instanzkonfiguration, als auch ihre <b>smoothio-Server</b> und deren Datenbankzugriff einsehen bzw. anpassen."
, 	"welcome_para4"		:	"<em>Hinweis:</em> dies ist ein Werkzeug zur &quot;niederen&quot; Daemon/Server-Verwaltung und &Uuml;berwachung. Weiterf&uuml;hrende &uuml;bergeordnete administrative Werkzeuge sowie detailliertere Dokumentation finden Sie in Ihren smoothio-Sites, sobald und solange Ihre Instanzen und deren Server &uuml;ber Ihren Webbrowser erreichbar sind."
,	"welcome_summary"	:	"Aktuell laufende smoothio-Server:"
};

