resources['en'] = {
	"_"					:	""
,	"info_for"			:	"for"
,	"info_arch"			:	"Architecture:"
,	"info_procs"		:	"Processors / cores:"
,	"subtab_config"		:	"Configuration"
,	"subtab_logs"		:	"Logs"
,	"subtab_overview"	:	"Overview"
,	"subtab_servers"	:	"Servers"
,	"tabs_insterror1"	:	"Could not load '"
,	"tabs_insterror2"	:	"' Instance:"
,	"tabs_title1"		:	"<b>"
,	"tabs_title2"		:	"</b> Instance"
,	"tabs_welcome"		:	"Welcome"
,	"tray_hint"			:	"smoothio Monitor"
,	"tray_menu_exit"	:	"Exit smoothio Monitor"
,	"tray_menu_show"	:	"Show smoothio Monitor"
,	"toolbar_refresh"	:	"Refresh"
,	"toolbar_restart"	:	"Restart"
,	"toolbar_start"		:	"Start"
,	"toolbar_status"	:	"smoothio Daemon Status:"
,	"toolbar_status_0"	:	"Stopped"
,	"toolbar_status_1"	:	"Running"
,	"toolbar_status_2"	:	"Starting"
,	"toolbar_status_3"	:	"Stopping"
,	"toolbar_status_10"	:	"Unknown"
,	"toolbar_stop"		:	"Stop"
, 	"toolbar_wait"		:	"(Detecting...)"
, 	"welcome_headline"	:	"How to use smoothio Monitor:"
, 	"welcome_para1"		:	"The navigation bar on the left shows your <b>smoothio Instances</b>. When the <b>smoothio Daemon</b> is running, it keeps these Instances alive and running."
, 	"welcome_para2"		:	"Each <b>smoothio Instance</b> is run in its own separate process and can host multiple <b>smoothio Servers</b> &mdash; ie. the Sites that your end users browse. Most often only one Instance is needed."
, 	"welcome_para3"		:	"To monitor or configure a <b>smoothio Instance</b>, select it on the left. This lets you review its log files, change its basic Instance configuration, plus manage its <b>smoothio Servers</b> and their database access."
, 	"welcome_para4"		:	"<em>Note:</em> this is a simple tool for very low-level daemon/server management and monitoring. Higher-level administrative tools and in-depth documentation are available via your smoothio Sites when your Instances and their Servers are running and accessible from your web browser."
,	"welcome_summary"	:	"Currently running smoothio Servers:"
};

