resources['en'] = {
	"___resfile_intro"	:	"THIS RES.*.JS FILE: the style of formatting used herein ensures no JSON-required commas or colons are ever missed. Copy & Paste for new resources."
,	"config_db"			:	"Database Access"
,	"config_db_am"		:	"Access mode"
,	"h_config_db_am"	:	"Embedded: smoothio runs its own local MongoDB server; database files reside in a smoothio Instance sub-folders.\n\nExternal: smoothio connects to a local or remote MongoDB database server that is entirely managed and run independently of this smoothio Instance."
,	"config_db_am_em"	:	"embedded"
,	"config_db_am_ex"	:	"external"
,	"config_db_host"	:	"DB server"
,	"h_config_db_host"	:	"In embedded mode, this is always 127.0.0.1.\n\nIn external mode, specify the IP address or host name of the MongoDB database server."
,	"config_db_port"	:	"Port"
,	"h_config_db_port"	:	"In embedded mode, specifies the TCP port number the local MongoDB server should accept connections at.\n\nIn external mode, specifies the TCP port number the local or remote MongoDB database server specified above is accepting connections at."
,	"config_db_path"	:	"Data path"
,	"h_config_db_path"	:	"Embedded mode only. Specifies the directory path (always relative to the Instance directory) to store the smoothio administrative and content databases."
,	"config_db_log"		:	"Log file path"
,	"h_config_db_log"	:	"Embedded mode only. Specifies the file path (always relative to the Instance directory) to store the smoothio MongoDB database log messages.\n\nTo avoid overwriting of old log files, you can include one asterisk [*] in the file path (to be expanded into date+time in the file name when the log file is created)."
,	"config_db_au"		:	"User name"
,	"h_config_db_au"	:	"External mode only. If the local or remote MongoDB database server requires authentication, specify the user name."
,	"config_db_ap"		:	"Password"
,	"h_config_db_ap"	:	"External mode only. If the local or remote MongoDB database server requires authentication, specify the password.\n\nCAUTION: this will be stored unencrypted in the plain-text instance.config file. Secure that file accordingly so that only you and the local smoothio service account can access it."
,	"config_db_ar"		:	"DB server requires authentication"
,	"config_dns"		:	"Pre-resolve Instance Server host names"
,	"config_dns_p"		:	"DNS &amp; Windows..."
,	"h_config_dns_p"	:	"Manual pre-resolving of Server host names, pre-empting DNS:\n\ncategorically *required* on Windows machines; not particularly useful on other systems. Manually mapping your local machine name as well as 'localhost' to 127.0.0.1 is required under Windows in order to properly start up the Servers defined for this Instance, because whenever your machine does not have access to the DNS servers configured under _core\\bin\\windows\\etc\\resolv.conf (ie. when Windows is offline), not even your machine name or 'localhost' will be properly resolved by smoothio\'s Cygwin environment and your Instance Servers cannot be started.\n\nEach line contains a mapping, consisting of a host name and its IP address, separated by a colon, such as mymachine:127.0.0.1\n\nThe special host name \'$localhostname\' always represents your local machine name. As a matter of course, only host names and IP addresses already assigned to this machine (via the appropriate OS network configuration) will work for binding your Instance Servers."
,	"config_log_path"	:	"Log file path"
,	"h_config_log_path"	:	"Specifies the file path (always relative to the Instance directory) to store the smoothio Instance log messages.\n\nTo avoid overwriting of old log files, you can include one asterisk [*] in the file path (to be expanded into date+time in the file name when the log file is created)."
,	"config_log_d"		:	"When logging errors, include their details"
,	"config_log_s"		:	"When logging errors, include their stack trace"
,	"config_log_lang"	:	"Default language"
,	"config_log_lang_o"	:	"Other:"
,	"h_config_log_lang"	:	"Specifies the language used for all log output produced by this smoothio Instance; at the same time this setting indicates the initial content language to be applied to newly created Servers and Sites in this Instance."
,	"config_rs_cf"		:	"Restart Instance"
,	"h_config_rs_cf"	:	"Tick this check-box option to have this Instance restart automatically when certain source files change, such as to-be-compiled script, style or configuration files in custom packages.\n\nRecommended for development environments while building custom packages. Not recommended for production systems, as the (arguably useless) monitoring of files requires additional system resources that would be better spent serving client requests.\n\nNOTE: regardless of this setting, this Instance ALWAYS auto-restarts itself when its instance.config file is modified."
,	"config_rs_cfl"		:	"if any of its core source files change"
,	"config_rs_fc"		:	"...on fatal crash"
,	"h_config_rs_fc"	:	"To prevent the process hosting this Instance from serving requests in an inconsistent, unreliable state, it will shut down on a \"fatal crash\" -- ie. any error condition that was not intercepted and cleanly handled by smoothio.\n\nIn such an event it is recommended to have this Instance auto-restart itself immediately, but clearly this behavior is not suitable for fatal errors occuring during start-up or very shortly afterwards.\n\nSpecify the minimum Instance uptime in seconds that must have passed for it to auto-restart itself on a fatal error. If the minimum uptime has not been reached on a fatal error, the Instance will simply shut down itself and will not be restarted until the next time smoothio Daemon gets (re)started."
,	"config_rs_fcl"		:	"restart only if uptime (in sec.) exceeds"
,	"config_unsaved"	:	"Changes <b>not yet saved</b>. <a href=\"#\" onclick=\"smio.configSaveChanges();\">Save now</a> (or <a href=\"#\" onclick=\"smio.refreshUI(false, false, true);\">Reload</a> present configuration)."
,	"config_info"		:	"To show a brief info tip about a setting, click its name."
,	"config_general"	:	"General"

,	"daemon_confirm1"	:	"If you proceed now, the smoothio Daemon will be shut down"
,	"daemon_confirm2"	:	" for approximately 2-6 seconds. This should not disrupt most current users too much, but will abort all in-progress client operations such as file uploads or downloads (for all Servers of all Instances)."
,	"daemon_confirm3"	:	". This will disconnect all current users and abort all in-progress client operations such as file uploads or downloads (for all Servers of all Instances)."
,	"daemon_confirm4"	:	"\n\nContinue anyway?"

,	"info_for"			:	"for"
,	"info_arch"			:	"Architecture:"
,	"info_procs"		:	"Processors / cores:"

,	"subtab_config"		:	"Configuration"
,	"subtab_logs"		:	"Logs"
,	"subtab_overview"	:	"Overview"
,	"subtab_servers"	:	"Servers"

,	"tabs_insterror1"	:	"Could not load '"
,	"tabs_insterror2"	:	"' Instance:"
,	"tabs_title1"		:	"<b>"
,	"tabs_title2"		:	"</b> Instance"
,	"tabs_welcome"		:	"Welcome"

,	"tray_hint"			:	"smoothio Monitor"
,	"tray_menu_exit"	:	"Exit smoothio Monitor"
,	"tray_menu_show"	:	"Show smoothio Monitor"

,	"toolbar_refresh"	:	"Refresh"
,	"toolbar_restart"	:	"Restart"
,	"toolbar_start"		:	"Start"
,	"toolbar_status"	:	"smoothio Daemon Status:"
,	"toolbar_status_0"	:	"Stopped"
,	"toolbar_status_1"	:	"Running"
,	"toolbar_status_2"	:	"Starting"
,	"toolbar_status_3"	:	"Stopping"
,	"toolbar_status_10"	:	"Unknown"
,	"toolbar_stop"		:	"Stop"
, 	"toolbar_wait"		:	"(Detecting...)"

, 	"welcome_headline"	:	"How to use smoothio Monitor:"
, 	"welcome_para1"		:	"The navigation bar on the left shows your <b>smoothio Instances</b>. When the <b>smoothio Daemon</b> is running, it keeps these Instances alive and running."
, 	"welcome_para2"		:	"Each <b>smoothio Instance</b> is run in its own separate process and can host multiple <b>smoothio Servers</b> &mdash; ie. the Sites that your end users browse. Often only one Instance is needed."
, 	"welcome_para3"		:	"To monitor or configure a <b>smoothio Instance</b>, select it on the left. This lets you review its log files, change its basic Instance configuration, plus manage its <b>smoothio Servers</b> and their database access."
, 	"welcome_para4"		:	"<em>Note:</em> this is a simple tool for very low-level Daemon/Server management and monitoring. Higher-level administrative tools and in-depth documentation are available via your smoothio Sites when your Instances and their Servers are running and accessible from your web browser."
,	"welcome_summary"	:	"Currently running smoothio Servers:"
};

