resources['en'] = {
	"_"					:	""
,	"config_db"			:	"Database Access"
,	"config_db_am"		:	"Access mode:"
,	"h_config_db_am"	:	"Embedded: smoothio runs its own local MongoDB instance; database files reside in a smoothio instance sub-folders.\n\nExternal: connect to a local or remote MongoDB database server managed and run outside of smoothio."
,	"config_db_am_em"	:	"embedded"
,	"config_db_am_ex"	:	"external"
,	"config_db_host"	:	"DB server:"
,	"h_config_db_host"	:	"In embedded mode, this is always 127.0.0.1.\n\nIn external mode, specify the IP address or host name of the MongoDB database server."
,	"config_db_port"	:	"Port:"
,	"h_config_db_port"	:	"In embedded mode, specify the port the local MongoDB instance should accept connections at.\n\nIn external mode, specify the port the local or remote MongoDB database server specified above is accepting connections at."
,	"config_db_path"	:	"Data path:"
,	"h_config_db_path"	:	"Embedded mode only. Specify the directory path (always relative to the instance directory) to store the smoothio administrative and content databases."
,	"config_db_log"		:	"Log file path:"
,	"h_config_db_log"	:	"Embedded mode only. Specify the file path (always relative to the instance directory) to store the smoothio MongoDB database logs.\n\nTo avoid overwriting of old log files, you can include one asterisk [*] in the file path (to be expanded into date and time in the file name when the log file is created)."
,	"config_db_au"		:	"User name:"
,	"h_config_db_au"	:	"External mode only. If the local or remote MongoDB database server requires authentication, specify the user name."
,	"config_db_ap"		:	"Password:"
,	"h_config_db_ap"	:	"External mode only. If the local or remote MongoDB database server requires authentication, specify the password.\n\nCAUTION: this will be stored unencrypted in the plain-text instance.config file. Secure that file accordingly so that only you and the smoothio user group can access it."
,	"config_db_ar"		:	"DB server requires authentication"
,	"config_unsaved"	:	"Configuration modifications not yet saved. <a href=\"#\" onclick=\"smio.daemonPrompt(true);\">Save now</a> (or <a href=\"#\">Reload</a> the present configuration)."
,	"config_info"		:	"To show a brief info tip about a setting, click its name. For more in-depth help, consult the smoothio product documentation."
,	"config_general"	:	"General"

,	"daemon_confirm1"	:	"If you proceed now, the smoothio Daemon will be shut down"
,	"daemon_confirm2"	:	" for approximately 2-6 seconds. This should not disrupt most current users too much, but will abort all in-progress client operations such as file uploads or downloads."
,	"daemon_confirm3"	:	". This will disconnect all current users and abort all in-progress client operations such as file uploads or downloads."
,	"daemon_confirm4"	:	"\n\nContinue anyway?"
,	"daemon_warnreset"	:	"Confirm server resets"

,	"info_for"			:	"for"
,	"info_arch"			:	"Architecture:"
,	"info_procs"		:	"Processors / cores:"

,	"subtab_config"		:	"Configuration"
,	"subtab_logs"		:	"Logs"
,	"subtab_overview"	:	"Overview"
,	"subtab_servers"	:	"Servers"

,	"tabs_insterror1"	:	"Could not load '"
,	"tabs_insterror2"	:	"' Instance:"
,	"tabs_title1"		:	"<b>"
,	"tabs_title2"		:	"</b> Instance"
,	"tabs_welcome"		:	"Welcome"

,	"tray_hint"			:	"smoothio Monitor"
,	"tray_menu_exit"	:	"Exit smoothio Monitor"
,	"tray_menu_show"	:	"Show smoothio Monitor"

,	"toolbar_refresh"	:	"Refresh"
,	"toolbar_restart"	:	"Restart"
,	"toolbar_start"		:	"Start"
,	"toolbar_status"	:	"smoothio Daemon Status:"
,	"toolbar_status_0"	:	"Stopped"
,	"toolbar_status_1"	:	"Running"
,	"toolbar_status_2"	:	"Starting"
,	"toolbar_status_3"	:	"Stopping"
,	"toolbar_status_10"	:	"Unknown"
,	"toolbar_stop"		:	"Stop"
, 	"toolbar_wait"		:	"(Detecting...)"

, 	"welcome_headline"	:	"How to use smoothio Monitor:"
, 	"welcome_para1"		:	"The navigation bar on the left shows your <b>smoothio Instances</b>. When the <b>smoothio Daemon</b> is running, it keeps these Instances alive and running."
, 	"welcome_para2"		:	"Each <b>smoothio Instance</b> is run in its own separate process and can host multiple <b>smoothio Servers</b> &mdash; ie. the Sites that your end users browse. Most often only one Instance is needed."
, 	"welcome_para3"		:	"To monitor or configure a <b>smoothio Instance</b>, select it on the left. This lets you review its log files, change its basic Instance configuration, plus manage its <b>smoothio Servers</b> and their database access."
, 	"welcome_para4"		:	"<em>Note:</em> this is a simple tool for very low-level daemon/server management and monitoring. Higher-level administrative tools and in-depth documentation are available via your smoothio Sites when your Instances and their Servers are running and accessible from your web browser."
,	"welcome_summary"	:	"Currently running smoothio Servers:"
};

