{
	"___resource_file_intro"		:	"This formatting ensures no JSON-required commas or colons are ever missed. To add new resources, copy&paste the next line."
,	"x"								:	"y"
, 	"nbsp"							:	"&nbsp;"
,	"title"							:	"Setting up your first Hub <a class='%s' href='%s'>at &#x279C; %s</a>"
,	"desc"							:	"This server does not contain any Hubs yet. Create one now:"
,	"url_hint"						:	"A Hub can have any URL address you like. The URL of your new Hub will be:\n\n%s://%s%s➜"
,	"owner_name"					:	"User name:"
,	"owner_namehint"				:	"eg. “JoeBloggs” or “admin” etc..."
,	"owner_pass"					:	"Password:"
,	"owner_pass2"					:	"Confirm:"
,	"owner_passhint"				:	"This is NOT transmitted or stored..."
,	"owner_pass2hint"				:	"...so pick one you will remember."
,	"owner_choice"					:	"The Hub owner specified above is:"
,	"owner_create"					:	"...a <i>new</i> <b>%s</b> user account"
,	"owner_login"					:	"...an <i>existing</i> <b>%s</b> account"
,	"hub_title"						:	"Hub title:"
,	"hub_titlehint"					:	"e.g. “Test hub”, “Project X”, “Personal” etc..."
,	"hub_hint"						:	"You can change the above Hub title at any time.<br/><br/>Initial default wallpaper for this Hub:"
,	"hub_create"					:	"Create Hub"
,	"steps_owner"					:	"➊  Specify owner"
,	"steps_template"				:	"➋  Select template"
,	"steps_finish"					:	"➌  Finish setup"
,	"steptitle_owner"				:	"1. Hub Owner"
,	"steptitle_template"			:	"2. Hub Template"
,	"steptitle_finish"				:	"3. Create Hub"
}

